name: Terraform Apply AWS (Debug OIDC)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  debug-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Request GitHub OIDC token
        id: oidc
        run: |
          echo "Fetching OIDC token..."
          TOKEN=$(curl -sLS \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL?audience=sts.amazonaws.com" | jq -r '.value')
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

          echo "--- Decoded Header ---"
          echo "$TOKEN" | cut -d "." -f1 | base64 -d
          echo "--- Decoded Payload ---"
          echo "$TOKEN" | cut -d "." -f2 | base64 -d

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
