name: Terraform Local Placeholder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Just a placeholder message in Actions
      - name: Skip AWS auth
        run: echo "AWS auth skipped. Run terraform init/plan/apply locally."

      - name: Terraform formatting check
        run: terraform fmt -check
