name: Debug OIDC Token

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  debug-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Request GitHub OIDC token and decode
        run: |
          echo "Requesting OIDC token..."
          TOKEN=$(curl -sLS \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}?audience=sts.amazonaws.com" | jq -r '.value')

          echo "--- Decoded Header ---"
          echo "$TOKEN" | cut -d "." -f1 | base64 -d

          echo "--- Decoded Payload ---"
          echo "$TOKEN" | cut -d "." -f2 | base64 -d
